version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        auth:
          username: lqp2792
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Hello World"